### PR TITLE
Potential fix for issue #6

### PR DESCRIPTION
**Pull request by g5t**
Fix the `mclRunMain` error by disabling the Java Virtual Machine

### CODE REVIEW

**Comment by mducle** [comment]
@g5t Cool! Thanks I hadn't thought to add `-nojvm`. The [docs](https://www.mathworks.com/help/compiler_sdk/cxx/mclrunmain.html) seems to hint at this but doesn't say so...

Does the plotting still work if you use `-nojvm`?

(PS. Don't worry about the failed tests on Windows and Macs. It's because of issues setting up the MCR runtime on the runners).

**Comment by g5t** [comment]
No, adding either `-nojvm` or `-nodisplay` prevents opening a plot window. 

To use the MATLAB plotting it seems one would need to actually create the Cocoa framework noted in your linked documentation. 
Initial attempts to shoehorn a call to `matlab::cpplib::runMain` into the `matlab_env` constructor have not been fruitful.

```cpp
      matlab_env::matlab_env(const std::u16string ctfname, std::string matlabroot) {
          _loadlibraries(matlabroot);
          auto mode = matlab::cpplib::MATLABApplicationMode::IN_PROCESS;
          // Specify MATLAB startup options
          std::vector<std::u16string> options = {u""};
          auto new_app = matlab::cpplib::initMATLABApplication(mode, options);
          int argc{0};
          const char * argv[] = {""};
          std::function<int(std::shared_ptr<matlab::cpplib::MATLABApplication>, const int, const char **)>
                  main = [&](std::shared_ptr<matlab::cpplib::MATLABApplication> app, const int c, const char ** v){
              _lib = matlab::cpplib::initMATLABLibrary(app, ctfname);
              return 0;
          };
          matlab::cpplib::runMain(main, std::move(new_app), argc, argv);
          _converter = pymat_converter(pymat_converter::NumpyConversion::WRAP);
      }
```

The `MatlabCppSharedLib.hpp` replacement in `libpymcr` is missing the necessary function declaration for `runMain` and attempting to insert the version in `MatlabCppSharedLib/detail/cppsharedlib_factory_impl.hpp` ultimately fails due to `cppsharedlib_run_main` not being linked in to the compiled module.

Further modifications to link in `libMatlabCppSharedLib.so` by adding the `${Matlab_ROOT_DIR}/runtime` contents to `${Matlab_LIBRARIES}` and then linking the compiled module against those, leads to a segmentation fault when calling a function in the ctf. Presumably due to the stored `_lib` going out of scope with the lambda function passed to `runMain`.

**Comment by mducle** [comment]
Thanks for trying @g5t to test it... I'll see if I can get things to work... I've got the mac-mini up and running again... but it's still only got 10.15 and complains that it's that is too old and no longer supported... :(

**Comment by g5t** [comment]
The latest commit changes the interface to expose the `options` vector, and uses `platform.system()` on the Python side to set sensible defaults (`'-nojvm'` on macOS, `''` everywhere else).
This precludes using MATLAB plotting on macOS, but does not prevent future developments to enable plotting parity between macOS, Windows, and Linux.

**Review by mducle — APPROVED** [review]
Looks good. Tests should pass when merged into `main` (CI was fixed in another PR).

**Pull request merged**
